# crypto-wallet-status task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.3

inputs:
- name: crypto-wallet-status

outputs:
- name: coverage-results

run:
  path: ./crypto-wallet-status/ci/scripts/unit-tests.sh
  # args: [-debug]
