# crypto-wallet-status task-unit-tests.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
- name: crypto-wallet-status

outputs:
- name: coverage-results

run:
  path: ./crypto-wallet-status/ci/scripts/unit-tests.sh
  # args: [-debug]
