# crypto-wallet-status task-build-push.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.3

inputs:
- name: crypto-wallet-status

outputs:
- name: dist

run:

  path: ./crypto-wallet-status/ci/scripts/build-push.sh
  # args: [-debug]
