# crypto-wallet-status task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19

inputs:
- name: crypto-wallet-status

run:
  path: ./crypto-wallet-status/ci/scripts/deploy.sh
  # args: [-debug]
