# crypto-wallet-status pipeline.yml

jobs:

- name: job-readme-github-pages
  plan:
  - get: crypto-wallet-status
    trigger: true
  - put: resource-slack-alert
    params:
      channel: '#jeff-builds'
      text: "From crypto-wallet-status: STARTED job-readme-github-pages in concourse ci."
  - put: resource-repo-status
    params: { state: "pending", description: "STARTED job-readme-github-pages in concourse ci.", commit: "crypto-wallet-status" }
  - task: task-readme-github-pages
    file: crypto-wallet-status/ci/tasks/task-readme-github-pages.yml
    on_success:
      do:
      - put: crypto-wallet-status
        params:
          repository: crypto-wallet-status-updated  
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From crypto-wallet-status: PASSED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "success", description: "PASSED job-readme-github-pages in concourse ci", commit: "crypto-wallet-status" }
    on_failure:
      do:
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From crypto-wallet-status: FAILED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "failure", description: "FAILED job-readme-github-pages in concourse ci", commit: "crypto-wallet-status" }

- name: job-unit-tests
  plan:
  - get: crypto-wallet-status
    trigger: true
    passed: [job-readme-github-pages]
  - put: resource-slack-alert
    params:
      channel: '#jeff-builds'
      text: "From crypto-wallet-status: STARTED job-unit-tests in concourse ci."
  - put: resource-repo-status
    params: { state: "pending", description: "STARTED job-unit-tests in concourse ci.", commit: "crypto-wallet-status" }
  - task: task-unit-tests
    file: crypto-wallet-status/ci/tasks/task-unit-tests.yml
    on_success:
      do:
      - put: crypto-wallet-status
        params:
          repository: crypto-wallet-status  
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text_file: coverage-results/test_coverage.txt
          text: |
            From crypto-wallet-status: PASSED job-unit-tests in concourse ci. 
            $TEXT_FILE_CONTENT
      - put: resource-repo-status
        params: { state: "success", description: "PASSED job-unit-tests in concourse ci", commit: "crypto-wallet-status" }
    on_failure:
      do:
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From crypto-wallet-status: FAILED job-unit-tests in concourse ci."
      - put: resource-repo-status
        params: { state: "failure", description: "FAILED job-unit-tests in concourse ci.", commit: "crypto-wallet-status" }

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:

- name: crypto-wallet-status
  type: git
  source:
    #uri: https://github.com/jeffdecola/crypto-wallet-status
    uri: git@github.com:jeffdecola/crypto-wallet-status.git
    branch: master
    private_key: {{git_private_key}}
- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}} 
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/crypto-wallet-status 
    access_token: {{repo_github_token}}
